[project]
name = "font-codepoint-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fonttools>=4.61.1",
]

[project.scripts]
font-codepoint-checker = "font_codepoint_checker:main"
