[project]
name = "svg-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fonttools>=4.61.1",
    "pdfminer-six>=20260107",
    "pymupdf>=1.26.7",
]
